export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';

export const WISHLIST_ADD = 'WISHLIST_ADD';
export const WISHLIST_REMOVE = 'WISHLIST_REMOVE';

export const RATE = 'RATE';